feat(sign up): sign up screen
TradeDis/frontend pull request #4
Opened 2020-10-26 11:53 UTC by 17yongga

2020-10-26 12:29 UTC, 17yongga commented
**What was done?**
Story: TRAD-9 "As a user, I would like to be able to sign-up and log in for the platform to securely store my personal information and my trade history"
Task: TRAD-65 UI - Sign-up Page

    - Sign-up screen
    -  along with basic input validation

**Areas which need special reviewing attention**
    - Color scheme and style
    - Display of user-facing messages (such as success and failure to sign-up)
    - button navigating
**Testing**
Test out the sign-up feature by interacting with the sign-up screen, pay attention to the UX and point out the non-intuitiveness of any design choices or input validation that might still have not been implemented.

2020-10-26 14:07 UTC, j584lee98 requested changes

2020-10-26 14:07 UTC, j584lee98 commented on screens/SignUpScreen.tsx
> +                const message = Object.values(errors).map((field: any) => field.message).join(' / ')
NIT: Error message should be separated by a line break for better readability.

2020-10-26 14:07 UTC, j584lee98 commented on screens/SignUpScreen.tsx
> +                <TextInput
NIT: Should keep a DRY design and use a map to return each text input instead of hard coding each one for all fields.

2020-10-26 14:07 UTC, j584lee98 commented on screens/SignUpScreen.tsx
> +            .post("http://localhost:3000/api/v1/users", user)
NIT: Try not to hard code api endpoints. Instead access the endpoint from the .env file.

2020-10-26 14:07 UTC, j584lee98 commented on screens/SignUpScreen.tsx
> +export default function NewPostScreen() {
Change name to SignUpScreen

2020-10-26 14:07 UTC, j584lee98 commented on screens/SignUpScreen.tsx
> +    const createPosting = () => {
Change to createUser

2020-10-26 14:16 UTC, 17yongga commented on screens/SignUpScreen.tsx
> +                const message = Object.values(errors).map((field: any) => field.message).join(' / ')
Yea I am having trouble doing that here, any suggestions?

2020-10-26 14:20 UTC, alanwu4321 commented on screens/SignUpScreen.tsx
> +                const message = Object.values(errors).map((field: any) => field.message).join(' / ')
Try to use `\n` to add line break

2020-10-26 14:22 UTC, 17yongga commented on screens/SignUpScreen.tsx
> +                const message = Object.values(errors).map((field: any) => field.message).join(' / ')
![Screen Shot 2020-10-26 at 7 19 11 AM](https://user-images.githubusercontent.com/16071999/97184201-e7010a80-175b-11eb-8d3a-77b01c2a58ea.png)
Worked! I was using /n

2020-10-26 14:43 UTC, 17yongga commented on screens/SignUpScreen.tsx
> +export default function NewPostScreen() {
Fixed

2020-10-26 14:44 UTC, 17yongga commented on screens/SignUpScreen.tsx
> +    const createPosting = () => {
Fixed

2020-10-26 15:10 UTC, alanwu4321 commented on screens/SignUpScreen.tsx
> +            .post("http://localhost:3000/api/v1/users", user)
This is addressed in commit https://github.com/TradeDis/frontend/pull/5/commits/4c000bdf7018765a32a7ead7b970690bb66d5f22

2020-11-04 11:40 UTC, alanwu4321 approved these changes

2020-11-04 11:53 UTC, merged